ProjektFit/Controllers/BmiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjektFit.Models;
using static ProjektFit.Models.BmiModel;

namespace ProjektFit.Controllers
{
    [Authorize]
    public class BmiController : Controller
    {
        
        [HttpGet]
        public IActionResult Index()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult bmi(BmiModel model)
        {

            string Wiadomosc="";
            double bmiliczba;

            //bmiliczba = (model.Waga / (model.Wzrost * model.Wzrost))/10000;
            int waga = model.Waga;
            int wzrost = model.Wzrost;
            wzrost = wzrost * wzrost;
            ViewBag.Resulttrzy = wzrost;
            waga = (waga*10000);
            ViewBag.Resultcztery = waga;
            bmiliczba = waga / wzrost;
            ViewBag.Resultpiec = bmiliczba;

            if (model.Wzrost != 0 && model.Waga != 0  )
            {
                if (bmiliczba <= 16)
                {
                    Wiadomosc = "wygłodzenie";
                }
                if (bmiliczba > 16 && bmiliczba <= 17)
                {
                    Wiadomosc = "wychudzenie";
                }
                if (bmiliczba <= 18.5 && bmiliczba > 17)
                {
                    Wiadomosc = "niedowaga";
                }
                if (bmiliczba <= 25 && bmiliczba > 18.5)
                {
                    Wiadomosc = "wartość prawidłowa";
                }
                if (bmiliczba <= 30 && bmiliczba > 25)
                {
                    Wiadomosc = "nadwaga";
                }
                if (bmiliczba <= 35 && bmiliczba > 30)
                {
                    Wiadomosc = "I stopień otyłości";
                }
                if (bmiliczba <= 40 && bmiliczba > 35)
                {
                    Wiadomosc = "II stopień otyłości";
                }
                if (bmiliczba > 40)
                {
                    Wiadomosc = "otyłość skrajna";
                }
           }

            //else
            //{
            //   Wiadomosc = "Wprowadź dane";
            //}

            ViewBag.Resultdwa = bmiliczba;
            ViewBag.Result = Wiadomosc;
            return View("Index");
        }
    }
}

ProjektFit/Controllers/CalculatorBMRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjektFit.Models;
using static ProjektFit.Models.CalculatorBMR;

namespace ProjektFit.Controllers
{
    [Authorize]
    public class CalculatorBMRController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(CalculatorBMR model)
        {
            double BMR = (9.99 * model.Weight) + (6.25 * model.Height) - (4.92 * model.Age);
            if (model.Gender==Genderr.Female)
            {
                BMR = BMR - 161;
                if(model.Activity==Activityy.Negligible)
                {
                    BMR = BMR * 1.0;
                }
                else if (model.Activity == Activityy.VerySmall)
                {
                    BMR = BMR * 1.2;              
                }
                else if (model.Activity == Activityy.Little)
                {
                    BMR = BMR * 1.4;
                }
                else if (model.Activity == Activityy.Moderate)
                {
                    BMR = BMR * 1.6;
                }
                else if (model.Activity == Activityy.Big)
                {
                    BMR = BMR * 1.8;
                }
                else if (model.Activity == Activityy.VeryBig)
                {
                    BMR = BMR * 2.0;
                }

            }
            else
            {
                BMR = BMR+5;
                if (model.Activity == Activityy.Negligible)
                {
                    BMR = BMR * 1.0;
                }
                else if (model.Activity == Activityy.VerySmall)
                {
                    BMR = BMR * 1.2;
                }
                else if (model.Activity == Activityy.Little)
                {
                    BMR = BMR * 1.4;
                }
                else if (model.Activity == Activityy.Moderate)
                {
                    BMR = BMR * 1.6;
                }
                else if (model.Activity == Activityy.Big)
                {
                    BMR = BMR * 1.8;
                }
                else if (model.Activity == Activityy.VeryBig)
                {
                    BMR = BMR * 2.0;
                }
            }
            ViewBag.Result = BMR;
            return View();
        }
    }
}

ProjektFit/Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjektFit.Models;
using ProjektFit.Data;
using static Microsoft.AspNetCore.Hosting.Internal.HostingApplication;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.AspNetCore.Authorization;

namespace ProjektFit.Controllers
{
    [Authorize]
    public class ChartsController : Controller
    {
        private readonly ChartsContext _context;

        public ChartsController(ChartsContext context)
        {
            _context = context;
        }

        // GET: Charts
        public async Task<IActionResult> Index()
        {
            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var query = await _context.Charts.Where(m => m.UserId == currentUserId).ToListAsync();

            return View(query);
        }

        // GET: Charts/Create
        public IActionResult Create()
        {

            return View();

        }

        // POST: Charts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChartsId,UserId,Waga,ObwodWKlatcePiersiowej,ObwodWPasie")] Charts charts)
        {
            if (ModelState.IsValid)
            {
                charts.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                _context.Add(charts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(charts);
        }

        // GET: Charts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charts = await _context.Charts.FindAsync(id);
            if (charts == null)
            {
                return NotFound();
            }
            TempData["OwnerId"] = charts.UserId;
            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (currentUserId == charts.UserId)
            {
                return View(charts);
            }
            else
            {
                return NotFound();
            }
        }

        // POST: Charts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ChartsId,UserId,Waga,ObwodWKlatcePiersiowej,ObwodWPasie")] Charts charts)
        {
            if (id != charts.ChartsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    charts.UserId = (string)TempData["OwnerId"];
                    _context.Update(charts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChartsExists(charts.ChartsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(charts);
        }

        // GET: Charts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charts = await _context.Charts
                .FirstOrDefaultAsync(m => m.ChartsId == id);
            if (charts == null)
            {
                return NotFound();
            }

            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (currentUserId == charts.UserId)
            {
                return View(charts);
            }
            else
            {
                return NotFound();
            }
        }


        public IActionResult Expense([Bind("ChartsId,UserId,Waga,ObwodWKlatcePiersiowej,ObwodWPasie")] Charts charts)
        {
       
            return View();
        }

        // POST: Charts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var charts = await _context.Charts.FindAsync(id);
            _context.Charts.Remove(charts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChartsExists(int id)
        {
            return _context.Charts.Any(e => e.ChartsId == id);
        }
    }
}

ProjektFit/Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjektFit.Models;

namespace ProjektFit.Controllers
{
    [Authorize]
    public class MealsController : Controller
    {
        private readonly List<string> type = new List<string>(new string[] { "Breakfast", "Brunch", "Lunch", "Dinner", "Tea", "Supper"});
        private readonly MealsContext _context;
        protected IAuthorizationService AuthorizationService { get; }

        public MealsController(MealsContext context, IAuthorizationService authorizationService)
        {
            _context = context;
            AuthorizationService = authorizationService;
        }

        // GET: Meals
        public async Task<IActionResult> Index()
        {
            if (HttpContext.User.IsInRole("Admin")) ViewBag.Admin = true;
            else ViewBag.Admin = false;
            return View(await _context.Meals.ToListAsync());
        }

        // GET: Meals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meals = await _context.Meals
                .FirstOrDefaultAsync(m => m.MealsId == id);
            if (HttpContext.User.IsInRole("Admin"))
            {
                ViewBag.AbleToModify = true;
            }
            else
            {
                ViewBag.AbleToModify = false;
            }
            if (meals == null)
            {
                return NotFound();
            }

            return View(meals);
        }

        // GET: Meals/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            if (TempData["ModelState"] != null)
            {
                ModelState.AddModelError(string.Empty, (string)TempData["ModelState"]);
            }
            ViewData["Type"] = new SelectList(type);
            return View();
        }

        // POST: Meals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("MealsId,Name,Typeofday,Calories,Protein,Carbohydres,Fats,UserId")] Meals meals)
        {
            if (ModelState.IsValid)
            {
                if (HttpContext.User.IsInRole("Admin"))
                {
                    ViewBag.AbleToModify = true;
                }
                else
                {
                    ViewBag.AbleToModify = false;
                }
                meals.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                _context.Add(meals);
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            TempData["ModelState"] = "You must fill in all of the fields";
            return RedirectToAction("Create");
        }

        // GET: Meals/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var meals = await _context.Meals.FindAsync(id);
            ViewData["Type"] = new SelectList(type);
            TempData["UserId"] = meals.UserId;
            if (meals == null)
            {
                return NotFound();
            }
            return View(meals);
        }

        // POST: Meals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MealsId,Name,Typeofday,Calories,Protein,Carbohydres,Fats")] Meals meals)
        {
            if (id != meals.MealsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    meals.UserId = (string)TempData["UserId"];
                    _context.Update(meals);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MealsExists(meals.MealsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = meals.MealsId });
            }
            return View(meals);
        }

        // GET: Meals/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (HttpContext.User.IsInRole("Admin"))
            {
                ViewBag.AbleToModify = true;
            }
            else
            {
                ViewBag.AbleToModify = false;
            }
            var meals = await _context.Meals
                .FirstOrDefaultAsync(m => m.MealsId == id);
            if (meals == null)
            {
                return NotFound();
            }

            return View(meals);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meals = await _context.Meals.FindAsync(id);
            _context.Meals.Remove(meals);
            if (meals == null)
            {
                return NotFound();
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MealsExists(int id)
        {
            return _context.Meals.Any(e => e.MealsId == id);
        }
    }
}

ProjektFit/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<?xml version="1.0" encoding="ISO-8859-2" ?>
<!DOCTYPE html
          PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl" style="height: 100%">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2" />
</head>
<body style="margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden">

    <div style="position: absolute; z-index: 2; width: 100%; height: 100%; overflow: auto">
        <div style="margin: 10px">

            <html>
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>@ViewData["Title"] - ProjektFit</title>
                <environment include="Development">
                    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
                </environment>
                <environment exclude="Development">
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
                          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                          crossorigin="anonymous"
                          integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
                </environment>
                <link rel="stylesheet" href="~/css/site.css" />
            </head>
            <body style="background:url(background.png)">
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjektFit</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                <partial name="_LoginPartial" />
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                                    </li>

                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercises" asp-action="Index">Exercises</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="TrainingPlans" asp-action="Index">Training Plans</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Meals" asp-action="Index">Meals</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Bmi" asp-action="Index">BMI</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="CalculatorBMR" asp-action="Index">BMR</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Charts" asp-action="Index">Measurements</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </nav>
                </header>
                <div class="container">
                    <partial name="_CookieConsentPartial" />
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
                <environment include="Development">
                    <script src="~/lib/jquery/dist/jquery.js"></script>
                    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
                </environment>
                <environment exclude="Development">
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                            asp-fallback-test="window.jQuery"
                            crossorigin="anonymous"
                            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
                    </script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                            crossorigin="anonymous"
                            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
                    </script>
                </environment>
                <script src="~/js/site.js" asp-append-version="true"></script>

                @RenderSection("Scripts", required: false)
            </body>
        </html>
    </div>
</div>

</body>
</html>
	</div>
</div>

<div><img src="~/css/telko.jpg" alt="" style="width: 100%; height: 100%; position: absolute; left: 0; top: 0; z-index: 1" /></div>

</html>